
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

//#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT

#define AUTO_SHIFT_TIMEOUT 250
#define NO_AUTO_SHIFT_ALPHA

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define NO_MUSIC_MODE
#define LAYER_STATE_8BIT
